### ISSUE TITLE
OT-AccountCreation

### ISSUE THREAD

**Issue by frlzjosh** [Off-Top-App/off-top-flutter#26]
WHAT TO DO:
1. You will need to create a screen/pop-up component that appears after a user signs into the app for the first time. 
2. after logging in and querying that user's data and we see that the data is null, then this means that we don't have their information in our database. Which means you will need to redirect to this component so that they can provide us their information
3. We actually don't have a mockup of how we would like this to look like so maybe make a prototype of figma before developing. 

DONE: 
1. You are able to insert data after logging in for the first time to the app through this API http://localhost:9000/setUser. Info on how to use this API is here: https://github.com/Off-Top-App/off-top-java/pull/9
2. Make sure you see the data appear into our database

**Comment by txt020** [comment]
@frlzjosh Do you want me to create the pop-up functions in flutter?
